services:
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    container_name: fastapi_backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres_db
      - ADMINER_DEFAULT_DRIVER=pgsql
    depends_on:
      - postgres
    restart: unless-stopped

  proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - 80:80
      - 8090:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    depends_on:
      - postgres
      - frontend
      - backend
      - adminer

volumes:
  postgres_data:
  data:
  letsencrypt: